<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[start1 starts]]>
    </line>
    <line>
      <![CDATA[start1 ends]]>
    </line>
    <line>
      <![CDATA[test1 starts]]>
    </line>
    <line>
      <![CDATA[test1 ends]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="28145" started-at="2020-05-07T17:27:38Z" finished-at="2020-05-07T17:28:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="28145" started-at="2020-05-07T17:27:38Z" finished-at="2020-05-07T17:28:06Z">
      <class name="Testng.P6_softassert">
        <test-method status="FAIL" signature="start1()[pri:0, instance:Testng.P6_softassert@7c16905e]" name="start1" duration-ms="27992" started-at="2020-05-07T22:57:38Z" finished-at="2020-05-07T22:58:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [Booooooogle] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Booooooogle] but found [Google]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Testng.P6_softassert.start1(P6_softassert.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[start1 starts]]>
            </line>
            <line>
              <![CDATA[start1 ends]]>
            </line>
          </reporter-output>
        </test-method> <!-- start1 -->
        <test-method status="PASS" signature="test1()[pri:0, instance:Testng.P6_softassert@7c16905e]" name="test1" duration-ms="2" started-at="2020-05-07T22:58:06Z" finished-at="2020-05-07T22:58:06Z">
          <reporter-output>
            <line>
              <![CDATA[test1 starts]]>
            </line>
            <line>
              <![CDATA[test1 ends]]>
            </line>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- Testng.P6_softassert -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
